# User choices are data. Package operations always use the fixed WinGet argument contract.
function Set-ManagerDataDirectory {
    param([string]$Path)
    $script:ManagerDataDirectory=if ($Path) {[IO.Path]::GetFullPath($Path)} else {''}
}

function ConvertTo-ManagerToolConfiguration {
    param($Configuration)
    if ($null -eq $Configuration) {throw 'Programlisten er tom eller ugyldig.'}
    if ($Configuration.Schema -and $Configuration.Schema -ne 1) {throw 'Programlisten har et ukendt format.'}
    $custom=@();$keys=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    $packages=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach ($tool in (Get-BuiltInToolCatalog)) {
        [void]$keys.Add($tool.Key)
        if ($tool.PackageId) {[void]$packages.Add("$(if ($tool.PackageSource) {$tool.PackageSource} else {'winget'})/$($tool.PackageId)")}
    }
    if (@($Configuration.CustomTools).Count -gt 50) {throw 'Der kan højst tilføjes 50 egne programmer.'}
    foreach ($entry in @($Configuration.CustomTools)) {
        if ($null -eq $entry) {continue}
        if ($entry.Key -cnotmatch '^custom_[a-z0-9_]{1,64}$' -or -not $keys.Add([string]$entry.Key)) {throw 'Et eget program har en ugyldig eller gentaget nøgle.'}
        $name=[string]$entry.Name;$launchName=[string]$entry.LaunchName
        if (-not $name.Trim() -or $name.Length -gt 64 -or $name -match '[\x00-\x1f\x7f]') {throw 'Programnavnet skal være 1–64 tegn uden linjeskift.'}
        if ($entry.Type -notin @('App','CLI') -or $entry.PackageSource -notin @('winget','msstore')) {throw 'Vælg App/CLI og kilden winget eller msstore.'}
        if ($entry.PackageId -cnotmatch '^[A-Za-z0-9][A-Za-z0-9._+-]{0,119}$') {throw 'Pakke-id må kun indeholde bogstaver, tal, punktum, bindestreg, plus og underscore.'}
        if (-not $packages.Add("$($entry.PackageSource)/$($entry.PackageId)")) {throw 'Denne pakke findes allerede i programlisten.'}
        if ($launchName.Length -gt 100 -or $launchName -match '[\x00-\x1f\x7f*?\[\]]') {throw 'Startmenu-navnet skal være et præcist navn uden jokertegn.'}
        $custom+=@{Key=[string]$entry.Key;Name=$name.Trim();Type=[string]$entry.Type;PackageId=[string]$entry.PackageId;PackageSource=[string]$entry.PackageSource;LaunchName=$launchName.Trim()}
    }
    $hidden=@(foreach ($key in @($Configuration.HiddenKeys)) {
        if ($key -isnot [string] -or -not $keys.Contains($key)) {throw 'Et skjult program findes ikke i programlisten.'}
        $key
    }) | Select-Object -Unique
    return @{Schema=1;HiddenKeys=@($hidden);CustomTools=@($custom)}
}

function Get-ManagerToolConfiguration {
    $default=@{Schema=1;HiddenKeys=@();CustomTools=@()}
    if (-not $script:ManagerDataDirectory) {return $default}
    $path=Join-Path $script:ManagerDataDirectory 'tools.json'
    if (-not (Test-Path -LiteralPath $path)) {return $default}
    if ((Get-Item -LiteralPath $path).Length -gt 256KB) {throw 'Programlisten er for stor.'}
    return ConvertTo-ManagerToolConfiguration (Get-Content -LiteralPath $path -Raw | ConvertFrom-Json -AsHashtable -ErrorAction Stop)
}

function Save-ManagerToolConfiguration {
    param($Configuration)
    if (-not $script:ManagerDataDirectory) {throw 'Datamappen til programlisten er ikke valgt.'}
    $valid=ConvertTo-ManagerToolConfiguration $Configuration
    Save-ManagerJson (Join-Path $script:ManagerDataDirectory 'tools.json') $valid
}

function Get-ToolCatalog {
    param([switch]$IncludeHidden)
    $configuration=Get-ManagerToolConfiguration
    $tools=@(Get-BuiltInToolCatalog)
    foreach ($entry in $configuration.CustomTools) {
        $tool=@{};foreach ($key in $entry.Keys) {$tool[$key]=$entry[$key]}
        $tool.Format='winget';$tool.Source="WinGet · $($tool.PackageSource) · $($tool.PackageId)"
        $tools+=$tool
    }
    foreach ($tool in $tools) {
        if ($IncludeHidden -or $tool.Key -notin $configuration.HiddenKeys) {$tool}
    }
}

function Test-ManagerAppId {
    param([string]$AppId)
    return $AppId -cmatch '^[A-Za-z0-9][A-Za-z0-9._-]{1,120}![A-Za-z0-9._-]{1,100}$' -or
        $AppId -match '^Microsoft\.AutoGenerated\.\{[0-9a-f-]{36}\}$' -or
        $AppId -cmatch '^[A-Za-z][A-Za-z0-9_-]*(?:\.[A-Za-z0-9_-]+){1,8}$'
}

function Find-ManagerLaunchTarget {
    param($Tool)
    if ($Tool.Type -ne 'App') {return $null}
    $name=if ($Tool.LaunchName) {$Tool.LaunchName} else {switch ($Tool.Key) {'codex_app' {'ChatGPT'} 'claude_app' {'Claude'} 'antigravity_app' {'Antigravity'} default {$Tool.Name}}}
    $matches=@(Get-StartApps -ErrorAction Stop | Where-Object {
        $_.Name -eq $name -and (Test-ManagerAppId $_.AppID) -and
        ($Tool.Key -ne 'codex_app' -or $_.AppID -like 'OpenAI.Codex_2p2nqsd0c76g0!*')
    })
    if ($matches.Count -eq 1) {return $matches[0]}
    return $null
}

function Start-ManagerApp {
    param($Tool)
    $target=Find-ManagerLaunchTarget $Tool
    if (-not $target) {throw 'Appen har ikke én entydig genvej i Startmenuen. Angiv dens præcise Startmenu-navn under Programmer.'}
    $start=[Diagnostics.ProcessStartInfo]::new()
    $start.FileName=Join-Path $env:SystemRoot 'explorer.exe';$start.UseShellExecute=$false
    $start.ArgumentList.Add("shell:AppsFolder\$($target.AppID)")
    $process=[Diagnostics.Process]::Start($start)
    if ($process) {$process.Dispose()}
}
