$ErrorActionPreference='Stop'
. "$PSScriptRoot/../updater-core.ps1"
$script:assertions=0
function Assert-Catalog($Condition,[string]$Message) {if (-not $Condition) {throw $Message};$script:assertions++}
$state=Join-Path $PSScriptRoot ('../artifacts/catalog-'+[guid]::NewGuid().ToString('N'))
Set-ManagerDataDirectory $state
$default=@(Get-ToolCatalog)
Assert-Catalog ($default.Count -eq 7) 'Defaults lost the original seven tools'
$custom=@{Key='custom_test';Name='Example Editor';Type='App';PackageId='Example.Editor';PackageSource='winget';LaunchName='Example Editor'}
$config=@{Schema=1;HiddenKeys=@('codex');CustomTools=@($custom)}
Save-ManagerToolConfiguration $config
$active=@(Get-ToolCatalog)
Assert-Catalog ($active.Count -eq 7 -and 'codex' -notin $active.Key -and 'custom_test' -in $active.Key) 'Custom addition or hiding did not apply'
Assert-Catalog (@(Get-ToolCatalog -IncludeHidden).Count -eq 8) 'Hidden tool cannot be restored'
$saved=Get-ManagerToolConfiguration
Assert-Catalog ($saved.CustomTools.Count -eq 1 -and $saved.HiddenKeys -contains 'codex') 'Selection was not persisted'
foreach ($change in @(@('Key','../../bad'),@('PackageId','--all'),@('PackageId','Example;exit'),@('PackageSource','untrusted'),@('Name',"bad`nname"),@('LaunchName','*'),@('Type','Script'))) {
    $bad=$custom.Clone();$bad[$change[0]]=$change[1];$rejected=$false
    try {Save-ManagerToolConfiguration @{HiddenKeys=@();CustomTools=@($bad)}} catch {$rejected=$true}
    Assert-Catalog $rejected "Unsafe custom configuration accepted: $($change[0])"
}
$rejected=$false
try {Save-ManagerToolConfiguration @{HiddenKeys=@();CustomTools=@($custom,$custom)}} catch {$rejected=$true}
Assert-Catalog $rejected 'Duplicate custom identity accepted'
Assert-Catalog ((Get-ManagerToolConfiguration).HiddenKeys -contains 'codex') 'Failed validation overwrote the previous file'
Save-ManagerToolConfiguration @{HiddenKeys=@((Get-ToolCatalog -IncludeHidden).Key);CustomTools=@($custom)}
Assert-Catalog (@(Get-ToolCatalog).Count -eq 0) 'Not all tools can be hidden'
Save-ManagerToolConfiguration @{HiddenKeys=@();CustomTools=@($custom)}
Assert-Catalog (@(Get-ToolCatalog).Count -eq 8) 'Default tool cannot be restored without losing custom tool'
$script:startApps=@([pscustomobject]@{Name='Example Editor';AppID='Example.App_abcdefghijklm!App'})
function Get-StartApps {$script:startApps}
$target=Find-ManagerLaunchTarget $custom
Assert-Catalog ($target.AppID -eq 'Example.App_abcdefghijklm!App') 'Exact Startmenu app not found'
$script:startApps+=@([pscustomobject]@{Name='Example Editor';AppID='Example.Other_abcdefghijklm!App'})
Assert-Catalog ($null -eq (Find-ManagerLaunchTarget $custom)) 'Ambiguous Startmenu app was selected silently'
$script:startApps=@([pscustomobject]@{Name='Example Editor';AppID='https://untrusted.example/'})
Assert-Catalog ($null -eq (Find-ManagerLaunchTarget $custom)) 'An arbitrary URL was accepted as app identity'
$script:startApps=@([pscustomobject]@{Name='Example Editor';AppID='Microsoft.AutoGenerated.{01234567-89AB-CDEF-0123-456789ABCDEF}'})
Assert-Catalog ($null -ne (Find-ManagerLaunchTarget $custom)) 'Desktop Startmenu identity was rejected'
$script:startApps=@([pscustomobject]@{Name='Example Editor';AppID='electron.app.Example'})
Assert-Catalog ($null -ne (Find-ManagerLaunchTarget $custom)) 'Registered Electron Startmenu identity was rejected'
$script:installerCalls=0
function Find-ToolExecutable {'winget.exe'}
function Invoke-ToolProcess {param($FilePath,$Arguments,$TimeoutSeconds)
    if ($Arguments[0] -eq 'upgrade') {$script:installerCalls++;throw 'Unexpected installer'}
    if ($Arguments[0] -eq 'list') {return @{Success=$true;ExitCode=0;Output='Example Editor Example.Editor 1.0.0 1.2.0'}}
    throw 'Unexpected command'
}
$customCli=$custom.Clone();$customCli.Type='CLI';$customCli.Format='winget'
$status=Get-OneToolStatus $customCli
Assert-Catalog ($status.HasUpdate -and $status.Type -eq 'CLI' -and $status.Installed -eq '1.0.0') 'Custom CLI did not use its package provider'
Assert-Catalog ($script:installerCalls -eq 0) 'Detection ran installation'
Write-Output "PASS: $script:assertions catalog assertions. Evidence: $state"
